// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PierresAnimalShelter;

namespace PierresAnimalShelter.Migrations
{
    [DbContext(typeof(PierresAnimalShelterContext))]
    [Migration("20191107073746_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PierresAnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Description");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Description = "An orange tabby.",
                            Gender = "Male",
                            Name = "Tony",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 10,
                            Description = "A gray terrier mix.",
                            Gender = "Female",
                            Name = "Gretchen",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 4,
                            Description = "An orange tabby.",
                            Gender = "Male",
                            Name = "Nacho",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 1,
                            Description = "A white mouse.",
                            Gender = "Female",
                            Name = "Urusula",
                            Species = "Mouse"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
